DEPRECATED_ATTRS = [
    ("accept", ["form"]),
    ("align",
     ["caption", "col", "div", "embed", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "iframe", "img", "input", "legend",
      "object", "p", "table", "tbody", "thead", "tfoot", "td", "th", "tr"]),
    ("alink", ["body"]),
    ("allowtransparency", ["iframe"]),
    ("archive", ["object"]),
    ("axis", ["td", "th"]),
    ("background", ['body', 'table', 'thead', 'tbody', 'tfoot', 'tr', 'td', 'th']),
    ("bgcolor", ['body', 'table', 'td', 'th', 'tr']),
    ("bordercolor", ['table']),
    ("cellpadding", ['table']),
    ("cellspacing", ['table']),
    ("char", ['col', 'tbody', 'thead', 'tfoot', 'td', 'th', 'tr']),
    ("charoff", ['col', 'tbody', 'thead', 'tfoot', 'td', 'th', 'tr']),
    ("charset", ['a', 'link']),
    ("classid", ['object']),
    ("clear", ['br']),
    ("code", ['object']),
    ("codebase", ['object']),
    ("codetype", ['object']),
    ("color", ['hr']),
    ("compact", ['dl', 'ol', 'ul']),
    ("coords", ['a']),
    ("datafld",
     ['a', 'applet', 'button', 'div', 'fieldset', 'frame', 'iframe', 'img', 'input', 'label', 'legend', 'marquee',
      'object', 'param', 'select', 'span', 'textarea']),
    ("dataformatas",
     ['button', 'div', 'input', 'label', 'legend', 'marquee', 'object', 'option', 'select', 'span', 'table']),
    ("datapagesize", ['table']),
    ("datasrc",
     ['a', 'applet', 'button', 'div', 'frame', 'iframe', 'img', 'input', 'label', 'legend', 'marquee', 'object',
      'option', 'select', 'span', 'table', 'textarea']),
    ("declare", ['object']),
    ("event", ['script']),
    ("for", ['script']),
    ("frame", ['table']),
    ("frameborder", ['iframe']),
    ("height", ['td', 'th']),
    ("hspace", ['embed', 'iframe', 'img', 'input', 'object']),
    ("ismap", ['input']),
    ("link", ['body']),
    ("lowsrc", ['img']),
    ("marginbottom", ['body']),
    ("marginheight", ['body', 'iframe']),
    ("marginleft", ['body']),
    ("marginright", ['body']),
    ("margintop", ['body']),
    ("marginwidth", ['body', 'iframe']),
    ("methods", ['a', 'link']),
    ("nohref", ['area']),
    ("noshade", ['hr']),
    ("nowrap", ['td', 'th']),
    ("profile", ['head']),
    ("rules", ['table']),
    ("scheme", ['meta']),
    ("scope", ['td']),
    ("scrolling", ['iframe']),
    ("shape", ['a']),
    ("size", ['hr']),
    ("standby", ['object']),
    ("summary", ['table']),
    ("target", ['link']),
    ("text", ['body']),
    ("type", ['li', 'param', 'ul']),
    ("urn", ['a', 'link']),
    ("usemap", ['input']),
    ("valign", ['col', 'tbody', 'thead', 'tfoot', 'td', 'th', 'tr']),
    ("valuetype", ['param']),
    ("version", ['html']),
    ("vlink", ['body']),
    ("vspace", ['embed', 'iframe', 'img', 'input', 'object']),
    ("width", ['col', 'hr', 'pre', 'table', 'td', 'th']),
    ("name", ['embed', 'img', 'option']),
    ("border", ['object']),
]

# langauge script(language="javascript", case insensitive, allowed)
# name a(name="[a's element id]" allowed)
# border img(border="0" allowed)
